blank_issues_enabled: false

contact_links:
  - name: Issue Template
    url: https://github.com/BrainPix/BrainPix-front/issues/new/choose
    about: Please use the issue template to create a new issue.
